### ISSUE TITLE
Migrate lpd-fem repo into lpd-detector

### ISSUE THREAD

**Issue by MRichards99** [stfc-aeg/lpd-detector-forked#1]
The repo lpd-fem (which contains the FEM GUI) is stored on a local repository. As discussed with Tim, it would be nice to migrate that repo into this one. A potential challenge is retaining all the commit history from that repo (otherwise it would be as simple as copying some files across). It would be good to have clean up of this repo at the same time (there are some things from Excalibur that isn't used for LPD.

**Comment by timcnicholls** [comment]
This issue was moved to stfc-aeg/lpd-detector#1
