### ISSUE TITLE
Tidy up Python Code Styling - fem-gui

### ISSUE THREAD

**Issue by MRichards99** [stfc-aeg/lpd-detector-forked#2]
Most of the code in the lpd-fem repo uses camelCase, but a lot of Jack's work uses underscores (as per PEP8). It would be nice to refactor the code to use all underscores. This isn't high priority (nor is it particularly interesting) but could be good to do if there's time.

**Comment by MRichards99** [comment]
Some refactoring of variable names has taken place, however commenting code is now being done as I work with different sections of the code (as opposed to a few days _just_ commenting.

**Comment by timcnicholls** [comment]
This issue was moved to stfc-aeg/lpd-detector#2
